'use strict';
window.addEventListener('DOMContentLoaded', () => {
  const need = ['PDFLib','pdfjsLib','JSZip','Sortable'];
  const missing = need.filter(x => typeof window[x] === 'undefined');
  if (missing.length) { alert('網站部署尚未完成，缺少程式元件：' + missing.join(', ')); return; }
  pdfjsLib.GlobalWorkerOptions.workerSrc = 'libs/pdf.worker.min.js';
  initTabs(); initMerge(); initSplit(); initEdit(); initJpg(); initImages(); initRedact();
});
const qs = s => document.querySelector(s);
const { PDFDocument, degrees } = window.PDFLib || {};
function saveBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function setupDrop(label,input,handler){label.addEventListener('dragover',e=>{e.preventDefault();label.classList.add('drag')});label.addEventListener('dragleave',()=>label.classList.remove('drag'));label.addEventListener('drop',e=>{e.preventDefault();label.classList.remove('drag');handler([...e.dataTransfer.files])});input.addEventListener('change',e=>{handler([...e.target.files]);input.value=''})}
async function pdfJsFromFile(file){return await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise}
async function renderThumb(doc,n,canvas,scale=.32){const p=await doc.getPage(n),vp=p.getViewport({scale});canvas.width=vp.width;canvas.height=vp.height;await p.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise}
function parsePages(s,total){s=(s||'').trim();if(!s)return Array.from({length:total},(_,i)=>i+1);let out=[];for(const raw of s.split(',')){const part=raw.trim();if(!part)continue;if(part.includes('-')){let[a,b]=part.split('-').map(Number);if(!Number.isInteger(a)||!Number.isInteger(b))throw Error('頁碼格式錯誤');if(a>b)[a,b]=[b,a];for(let i=a;i<=b;i++)out.push(i)}else{const n=Number(part);if(!Number.isInteger(n))throw Error('頁碼格式錯誤');out.push(n)}}out=[...new Set(out)];if(out.some(n=>n<1||n>total))throw Error('頁碼超出範圍');return out}
function cardButton(text,cls,fn){const b=document.createElement('button');b.className=`btn ${cls} small`;b.textContent=text;b.type='button';b.addEventListener('click',fn);return b}
function initTabs(){document.querySelectorAll('.tool-card').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tool-card').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.workspace').forEach(x=>x.classList.remove('active'));b.classList.add('active');qs('#'+b.dataset.tool).classList.add('active')}))}
let mergeSources=[],mergeItems=[],mergeSortable;
function initMerge(){setupDrop(qs('#mergeDrop'),qs('#mergeInput'),async files=>{for(const f of files.filter(x=>x.type==='application/pdf'||x.name.toLowerCase().endsWith('.pdf'))){const si=mergeSources.length;mergeSources.push(f);const d=await pdfJsFromFile(f);for(let p=1;p<=d.numPages;p++)mergeItems.push({si,p,id:crypto.randomUUID()})}await renderMerge()});qs('#mergeClear').onclick=()=>{mergeSources=[];mergeItems=[];renderMerge()};qs('#mergeExport').onclick=mergeExport}
async function renderMerge(){const box=qs('#mergePages');box.innerHTML='';const docs={};for(let i=0;i<mergeItems.length;i++){const it=mergeItems[i],c=document.createElement('div');c.className='page-card';c.dataset.id=it.id;const thumb=document.createElement('div');thumb.className='page-thumb';const cv=document.createElement('canvas');thumb.appendChild(cv);const meta=document.createElement('div');meta.className='page-meta';meta.textContent=`${i+1}. ${mergeSources[it.si].name}｜原第 ${it.p} 頁`;const actions=document.createElement('div');actions.className='page-actions';actions.append(cardButton('刪除','danger',()=>{mergeItems=mergeItems.filter(x=>x.id!==it.id);renderMerge()}));c.append(thumb,meta,actions);box.appendChild(c);if(!docs[it.si])docs[it.si]=await pdfJsFromFile(mergeSources[it.si]);await renderThumb(docs[it.si],it.p,cv)}qs('#mergeStatus').textContent=`目前 ${mergeItems.length} 頁`;if(mergeSortable)mergeSortable.destroy();mergeSortable=Sortable.create(box,{animation:140,onEnd:()=>{const ids=[...box.children].map(x=>x.dataset.id);mergeItems=ids.map(id=>mergeItems.find(x=>x.id===id));renderMerge()}})}
async function mergeExport(){if(!mergeItems.length)return alert('請先加入 PDF');try{const docs=[];for(const f of mergeSources)docs.push(await PDFDocument.load(await f.arrayBuffer()));const out=await PDFDocument.create();for(const it of mergeItems){const[p]=await out.copyPages(docs[it.si],[it.p-1]);out.addPage(p)}saveBlob(new Blob([await out.save()],{type:'application/pdf'}),'合併重組.pdf')}catch(e){alert('合併失敗：'+e.message)}}
let splitFile=null;function initSplit(){qs('#splitInput').onchange=e=>{splitFile=e.target.files[0]||null;qs('#splitFileName').textContent=splitFile?splitFile.name:'尚未選擇'};qs('#splitExport').onclick=splitExport}
async function splitExport(){if(!splitFile)return alert('請選擇 PDF');try{const src=await PDFDocument.load(await splitFile.arrayBuffer()),total=src.getPageCount(),raw=qs('#splitRanges').value.trim();if(!raw)throw Error('請輸入拆分範圍');const chunks=raw.split(',').map(x=>x.trim()).filter(Boolean),zip=new JSZip();let idx=1;for(const ch of chunks){const pages=parsePages(ch,total),out=await PDFDocument.create();for(const n of pages){const[p]=await out.copyPages(src,[n-1]);out.addPage(p)}zip.file(`拆分_${String(idx++).padStart(2,'0')}_${ch}.pdf`,await out.save())}saveBlob(await zip.generateAsync({type:'blob'}),'PDF拆分.zip');qs('#splitStatus').textContent=`完成，共 ${chunks.length} 個 PDF`}catch(e){alert(e.message)}}
let editFile=null,editDocJs=null,editItems=[];function initEdit(){qs('#editInput').onchange=async e=>{editFile=e.target.files[0]||null;qs('#editFileName').textContent=editFile?editFile.name:'尚未選擇';if(!editFile)return;editDocJs=await pdfJsFromFile(editFile);editItems=Array.from({length:editDocJs.numPages},(_,i)=>({p:i+1,rot:0,del:false}));await renderEdit()};qs('#editExport').onclick=editExport}
async function renderEdit(){const box=qs('#editPages');box.innerHTML='';for(const it of editItems){const c=document.createElement('div');c.className='page-card'+(it.del?' deleted':'');const thumb=document.createElement('div');thumb.className='page-thumb';const cv=document.createElement('canvas');thumb.appendChild(cv);const meta=document.createElement('div');meta.className='page-meta';meta.textContent=`第 ${it.p} 頁｜旋轉 ${it.rot}°`;const actions=document.createElement('div');actions.className='page-actions';actions.append(cardButton('旋轉 90°','muted',()=>{it.rot=(it.rot+90)%360;renderEdit()}),cardButton(it.del?'保留':'刪除','danger',()=>{it.del=!it.del;renderEdit()}));c.append(thumb,meta,actions);box.appendChild(c);await renderThumb(editDocJs,it.p,cv)}qs('#editStatus').textContent=`保留 ${editItems.filter(x=>!x.del).length} / ${editItems.length} 頁`}
async function editExport(){if(!editFile)return alert('請選擇 PDF');try{const src=await PDFDocument.load(await editFile.arrayBuffer()),out=await PDFDocument.create();for(const it of editItems.filter(x=>!x.del)){const[p]=await out.copyPages(src,[it.p-1]);if(it.rot)p.setRotation(degrees(((p.getRotation().angle||0)+it.rot)%360));out.addPage(p)}if(!out.getPageCount())throw Error('至少保留一頁');saveBlob(new Blob([await out.save()],{type:'application/pdf'}),'修改後.pdf')}catch(e){alert(e.message)}}
let jpgFile=null;function initJpg(){qs('#jpgInput').onchange=e=>{jpgFile=e.target.files[0]||null;qs('#jpgFileName').textContent=jpgFile?jpgFile.name:'尚未選擇'};qs('#jpgExport').onclick=jpgExport}
async function jpgExport(){if(!jpgFile)return alert('請選擇 PDF');try{const d=await pdfJsFromFile(jpgFile),pages=parsePages(qs('#jpgRanges').value,d.numPages),scale=Number(qs('#jpgScale').value),zip=new JSZip();for(let i=0;i<pages.length;i++){qs('#jpgStatus').textContent=`轉換 ${i+1}/${pages.length}`;const p=await d.getPage(pages[i]),vp=p.getViewport({scale}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.92));zip.file(`page_${String(pages[i]).padStart(3,'0')}.jpg`,blob)}saveBlob(await zip.generateAsync({type:'blob'}),'PDF轉JPG.zip');qs('#jpgStatus').textContent='完成'}catch(e){alert(e.message)}}
let imgItems=[],imgSortable;function initImages(){setupDrop(qs('#imgDrop'),qs('#imgInput'),files=>{for(const f of files.filter(x=>/^image\/(jpeg|png)$/.test(x.type)))imgItems.push({f,id:crypto.randomUUID()});renderImages()});qs('#imgClear').onclick=()=>{imgItems=[];renderImages()};qs('#imgExport').onclick=imgExport}
function renderImages(){const box=qs('#imgPages');box.innerHTML='';imgItems.forEach((it,i)=>{const c=document.createElement('div');c.className='page-card';c.dataset.id=it.id;const thumb=document.createElement('div');thumb.className='page-thumb';const im=document.createElement('img');const u=URL.createObjectURL(it.f);im.src=u;im.onload=()=>URL.revokeObjectURL(u);thumb.appendChild(im);const meta=document.createElement('div');meta.className='page-meta';meta.textContent=`${i+1}. ${it.f.name}`;const actions=document.createElement('div');actions.className='page-actions';actions.append(cardButton('移除','danger',()=>{imgItems=imgItems.filter(x=>x.id!==it.id);renderImages()}));c.append(thumb,meta,actions);box.appendChild(c)});qs('#imgStatus').textContent=`目前 ${imgItems.length} 張圖片`;if(imgSortable)imgSortable.destroy();imgSortable=Sortable.create(box,{animation:140,onEnd:()=>{const ids=[...box.children].map(x=>x.dataset.id);imgItems=ids.map(id=>imgItems.find(x=>x.id===id));renderImages()}})}
async function imgExport(){if(!imgItems.length)return alert('請加入圖片');try{const out=await PDFDocument.create(),mode=qs('#paperMode').value;for(const it of imgItems){const bytes=await it.f.arrayBuffer(),im=it.f.type==='image/png'?await out.embedPng(bytes):await out.embedJpg(bytes),iw=im.width,ih=im.height;let pw,ph;if(mode==='a4p'){pw=595.28;ph=841.89}else if(mode==='a4l'){pw=841.89;ph=595.28}else{pw=iw;ph=ih}const page=out.addPage([pw,ph]),margin=mode==='original'?0:28,sc=Math.min((pw-2*margin)/iw,(ph-2*margin)/ih),w=iw*sc,h=ih*sc;page.drawImage(im,{x:(pw-w)/2,y:(ph-h)/2,width:w,height:h})}saveBlob(new Blob([await out.save()],{type:'application/pdf'}),'圖片合成.pdf')}catch(e){alert(e.message)}}
let redFile=null,redDoc=null,redPage=1,redRects={},redBaseScale=1.35,drawStart=null;function initRedact(){const cv=qs('#redactCanvas');qs('#redactInput').onchange=async e=>{redFile=e.target.files[0]||null;qs('#redactFileName').textContent=redFile?redFile.name:'尚未選擇';if(!redFile)return;redDoc=await pdfJsFromFile(redFile);redPage=1;redRects={};renderRedList();renderRedPage()};qs('#redactUndo').onclick=()=>{const a=redRects[redPage]||[];a.pop();renderRedList();renderRedPage()};qs('#redactClear').onclick=()=>{redRects[redPage]=[];renderRedList();renderRedPage()};qs('#redactExport').onclick=redactExport;cv.addEventListener('mousedown',e=>{if(redDoc)drawStart=canvasPos(e,cv)});cv.addEventListener('mouseup',e=>{if(!drawStart)return;const q=canvasPos(e,cv),x=Math.min(drawStart.x,q.x),y=Math.min(drawStart.y,q.y),w=Math.abs(q.x-drawStart.x),h=Math.abs(q.y-drawStart.y);drawStart=null;if(w>4&&h>4){(redRects[redPage]??=[]).push({x,y,w,h});renderRedList();renderRedPage()}})}
function canvasPos(e,cv){const r=cv.getBoundingClientRect();return{x:(e.clientX-r.left)*cv.width/r.width,y:(e.clientY-r.top)*cv.height/r.height}}
function renderRedList(){const box=qs('#redactList');box.innerHTML='';if(!redDoc)return;for(let i=1;i<=redDoc.numPages;i++){const d=document.createElement('div');d.className='redact-item'+(i===redPage?' active':'');d.textContent=`第 ${i} 頁｜遮蔽 ${(redRects[i]||[]).length} 處`;d.onclick=()=>{redPage=i;renderRedList();renderRedPage()};box.appendChild(d)}}
async function renderRedPage(){if(!redDoc)return;const cv=qs('#redactCanvas'),p=await redDoc.getPage(redPage),vp=p.getViewport({scale:redBaseScale});cv.width=vp.width;cv.height=vp.height;const ctx=cv.getContext('2d');await p.render({canvasContext:ctx,viewport:vp}).promise;ctx.fillStyle='#000';for(const r of(redRects[redPage]||[]))ctx.fillRect(r.x,r.y,r.w,r.h);qs('#redactStatus').textContent='用滑鼠拖曳框選要永久遮蔽的區域'}
async function redactExport(){if(!redDoc)return alert('請選擇 PDF');try{const out=await PDFDocument.create(),scale=2;for(let n=1;n<=redDoc.numPages;n++){qs('#redactStatus').textContent=`安全輸出 ${n}/${redDoc.numPages}`;const p=await redDoc.getPage(n),vp=p.getViewport({scale}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;const ctx=c.getContext('2d');await p.render({canvasContext:ctx,viewport:vp}).promise;ctx.fillStyle='#000';for(const r of(redRects[n]||[])){const k=scale/redBaseScale;ctx.fillRect(r.x*k,r.y*k,r.w*k,r.h*k)}const png=await new Promise(res=>c.toBlob(res,'image/png'));const emb=await out.embedPng(await png.arrayBuffer());const ptW=vp.width*72/(96*scale),ptH=vp.height*72/(96*scale),pg=out.addPage([ptW,ptH]);pg.drawImage(emb,{x:0,y:0,width:ptW,height:ptH})}saveBlob(new Blob([await out.save()],{type:'application/pdf'}),'隱私遮蔽_安全輸出.pdf');qs('#redactStatus').textContent='完成：已平面化輸出'}catch(e){alert(e.message)}}
